server {
  listen 80;
  server_name inoxpran.com www.inoxpran.com;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    add_header Content-Type text/plain;
    return 200 'OK';
  }
}
