@url_dev = http://localhost:3056/v1/api
@api_key = {{$dotenv PUBLIC_API_KEY}}
@test_email = {{$dotenv POSTMAN_TEST_EMAIL}}
@test_password = {{$dotenv POSTMAN_TEST_PASSWORD}}

### signup
POST {{url_dev}}/user/login
Content-Type: application/json
x-api-key: {{api_key}}

{
  "email": "{{test_email}}",
  "password": "{{test_password}}"
}
